services:
  app:
    build: .docker/php
    ports: ["8080:80"]
    volumes: ["./scr:/var/www/html"]
  db:
    image: jacobalberty/firebird:3.0
    environment: [ISC_PASSWORD=masterkey]
    volumes: ["./data:/firebird/data"]