CREATE DATABASE agenda_contatos;
USE agenda_contatos;

CREATE TABLE PESSOA (
    ID_PESSOA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE CIDADE (
    ID_CIDADE INT AUTO_INCREMENT PRIMARY KEY,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL
);

CREATE TABLE ENDERECO (
    ID_ENDERECO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PESSOA INT,
    ID_CIDADE INT,
    CEP VARCHAR(20) NOT NULL,
    RUA VARCHAR(100),
    BAIRRO VARCHAR(100),
    NUMERO VARCHAR(20),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA) ON DELETE CASCADE,
    FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
);

CREATE TABLE TELEFONE (
    ID_TELEFONE INT AUTO_INCREMENT PRIMARY KEY,
    ID_PESSOA INT,
    NUMERO VARCHAR(20),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA) ON DELETE CASCADE
);